# https://kind.sigs.k8s.io/docs/user/configuration/
# kind version v0.17.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
  # WARNING: It is _strongly_ recommended that you keep this the default (127.0.0.1) for security reasons.
  apiServerAddress: "192.168.86.42"
  apiServerPort: 6443
